---
- name: Install packages
  hosts: "{{ instance_name_template }}{{ substrate }}__juju__{{juju_version}}"
  gather_facts: yes
  become: yes
  vars:
    instance_name_template: "dmitry-ratushnyy_dev_server__"
    ansible_user: ubuntu

  tasks:
    - name: Install required packages
      package:
        name:
          - git
          - gcc
          - python3-venv
          - python3-pip
          - snapcraft
        state: present
        update_cache: yes
  
    - name: Add Helm GPG key
      ansible.builtin.apt_key:
        url: https://baltocdn.com/helm/signing.asc
        keyring: /usr/share/keyrings/helm.gpg

    - name: Install apt-transport-https
      ansible.builtin.apt:
        name: apt-transport-https
        state: present

    - name: Add Helm repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main"
        state: present
        filename: helm-stable-debian

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Helm
      ansible.builtin.apt:
        name: helm
        state: present

    - name: Install charmcraft
      ansible.builtin.command:
        cmd: "sudo snap install charmcraft --classic --revision 1349"
      become: yes

    - name: Pin charmcraft version
      ansible.builtin.command:
        cmd: "snap refresh charmcraft --hold=forever"
      become: yes

