---
- name: "Configure juju {{juju_version}} on {{substrate}} substrate"
  hosts: "{{ instance_name_template }}{{ substrate }}__juju__{{juju_version}}"
  vars:
    instance_name_template: "dmitry-ratushnyy_dev_server__"
    ansible_user: ubuntu
    substrate: "{{ substrate }}"
    juju_version: "{{ juju_version }}"
    
  tasks:
    - name: Include instance configuration
      include_vars:
        file: ../instance_config.yml

    - name: Include install_lxd tasks
      import_tasks: ../tasks/install_lxd.yml

    - name: Install Juju using snap
      ansible.builtin.snap:
        name: juju
        classic: yes
        state: present
      become: yes

    - name: Include juju bootstrap tasks
      import_tasks: ../tasks/juju_vm_bootstrap.yml