---
- name: "Configure juju {{juju_version}} on {{substrate}} substrate"
  hosts: "{{ instance_name_template }}{{ substrate }}__juju__{{juju_version}}"
  vars:
    instance_name_template: "dmitry-ratushnyy_dev_server__"
    ansible_user: ubuntu
    substrate: "{{ substrate }}"
    juju_version: "{{ juju_version }}"
    
  tasks:
    - name: Include instance configuration
      include_vars:
        file: ../instance_config.yml

    - name: Include install_lxd tasks
      import_tasks: ../tasks/install_lxd.yml

    - name: Install Juju using snap
      ansible.builtin.snap:
        name: juju
        classic: yes
        state: present
      become: yes

    - name: Include juju bootstrap tasks
      import_tasks: ../tasks/juju_vm_bootstrap.yml

#    - name: Fix build for charms
#      shell: |
#        mkdir -p ~/ga-charmcraft-cache
#        charm_repository_directory_inode=$(stat --format "%i" '${{ /home/ubuntu/development/src/mongodb-operator }}')
#        for container_name_with_inode in $(sg lxd -c "lxc --project charmcraft list --columns n --format csv")
#        do
#          # Disable charmcraft snap updates
#          # Workaround (unconfirmed) for https://github.com/canonical/charmcraft/issues/1202
#          sg lxd -c "lxc --project charmcraft start \"$container_name_with_inode\""
#          sg lxd -c "lxc --project charmcraft exec \"$container_name_with_inode\" -- bash -c 'while ! systemctl is-active snapd.service; do sleep 0.5; done'"
#          sg lxd -c "lxc --project charmcraft exec \"$container_name_with_inode\" -- snap refresh --hold=forever charmcraft"
#          sg lxd -c "lxc --project charmcraft stop \"$container_name_with_inode\""
#
#          # charmcraft 2.3.0 added a "base instance" LXC container that is not specific to a charm (and doesn't contain an inode)
#          if [[ $container_name_with_inode == charmcraft-* ]]
#          then
#            # LXC container is for a charm (not the "base instance")
#            # Replace inode with placeholder text "INODE"
#            container_name_without_inode="${container_name_with_inode//$charm_repository_directory_inode/INODE}"
#            sg lxd -c "lxc --project charmcraft move \"$container_name_with_inode\" \"$container_name_without_inode\""
#          else
#            # LXC container is the "base instance"
#            container_name_without_inode="$container_name_with_inode"
#          fi
#          # Use GitHub actions/cache compression
#          sg lxd -c "lxc --project charmcraft export --optimized-storage --compression none \"$container_name_without_inode\" ~/ga-charmcraft-cache/\"$container_name_without_inode\".tar"
#        done
#      args:
#        executable: /bin/bash