- name: Install MicroK8s
  ansible.builtin.snap:
    name: microk8s
    classic: yes
    channel: stable

- name: Add current user to microk8s group
  ansible.builtin.user:
    name: "{{ instance_user }}"
    groups: microk8s
    append: yes

- name: Create .kube directory
  ansible.builtin.file:
    path: "/home/{{ instance_user }}/.kube"
    state: directory
    owner: "{{ instance_user }}"
    group: "{{ instance_user }}"
  

- name: Enable MicroK8s add-ons
  ansible.builtin.shell: "microk8s.enable dns hostpath-storage ingress"

- name: Create alias for microk8s.kubectl
  ansible.builtin.shell: "snap alias microk8s.kubectl kubectl"

- name: Reboot the instance
  ansible.builtin.reboot:
    reboot_timeout: 300
    test_command: "whoami"

- name: Wait for SSH to become available
  ansible.builtin.wait_for_connection:
    delay: 60
    timeout: 300

- name: Check MicroK8s is ready
  ansible.builtin.shell: "microk8s.status --wait-ready"
  retries: 30
  delay: 10
  register: result
  until: result.rc == 0

