- name: Install MicroK8s
  ansible.builtin.snap:
    name: microk8s
    classic: yes
    channel: 1.25-strict

- name: Add current user to microk8s group
  ansible.builtin.user:
    name: "{{ instance_user }}"
    groups: snap_microk8s
    append: yes

- name: Enable MicroK8s add-ons
  ansible.builtin.shell: "microk8s.enable dns storage ingress"

- name: Create alias for microk8s.kubectl
  ansible.builtin.shell: "snap alias microk8s.kubectl kubectl"

- name: Reboot the instance
  ansible.builtin.reboot:
    reboot_timeout: 300
    test_command: "whoami"

- name: Wait for SSH to become available
  ansible.builtin.wait_for_connection:
    delay: 60
    timeout: 300

- name: Check MicroK8s is ready
  ansible.builtin.shell: "microk8s.status --wait-ready"
  retries: 30
  delay: 10
  register: result
  until: result.rc == 0

- name: Create .kube directory
  file:
    path: "/home/{{ instance_user }}/.kube"
    state: directory
    owner: "{{instance_user}}"
    group: "{{instance_user}}"
    mode: '0755'
  become_user: "{{ instance_user }}"

- name: Export config from microk8s to ~/.kube/config
  shell: "microk8s config > /home/{{ instance_user }}/.kube/config"
  args:
    executable: /bin/bash
  become_user: "{{ instance_user }}"

- name: Set permissions for kube config
  file:
    path: "/home/{{instance_user}}/.kube/config"
    owner: "{{ instance_user }}"
    group: "{{ instance_user }}"
    mode: '0600'
  become: yes